language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -e ."
  - "pip install -r requirements.txt"
  - "pip install -r dev_requirements.txt"
  - "pip install pyutilib"
# command to run tests
script: coverage run --source=ckanext.twitter setup.py nosetests
after_success: coveralls
